-- Limit, Offset & Fetch

SELECT * FROM person LIMIT 15;

SELECT * FROM person OFFSET 5;

SELECT * FROM person OFFSET 5 LIMIT 15;

SELECT * FROM person FETCH FIRST 8 ROWS ONLY;

SELECT * FROM person OFFSET 5 FETCH FIRST 8 ROWS ONLY;

SELECT * FROM person OFFSET 5 FETCH FIRST ROW ONLY;
