SELECT EXTRACT(CENTURY FROM NOW());

SELECT EXTRACT(YEAR FROM NOW());

SELECT EXTRACT(MONTH FROM NOW());

SELECT EXTRACT(DAY FROM NOW());

SELECT EXTRACT(DOW FROM NOW());

SELECT EXTRACT(HOUR FROM NOW());

SELECT EXTRACT(MINUTE FROM NOW());

SELECT EXTRACT(SECOND FROM NOW());
