export const REQUEST_GET_TODOS_PENDING = 'REQUEST_GET_TODOS_PENDING';
export const REQUEST_GET_TODOS_SUCCESS = 'REQUEST_GET_TODOS_SUCCESS';
export const REQUEST_GET_TODOS_FAILED = 'REQUEST_GET_TODOS_FAILED';

export const REQUEST_ADD_TODO_PENDING = 'REQUEST_ADD_TODO_PENDING';
export const REQUEST_ADD_TODO_SUCCESS = 'REQUEST_ADD_TODO_SUCCESS';
export const REQUEST_ADD_TODO_FAILED = 'REQUEST_ADD_TODO_FAILED';

export const REQUEST_UPDATE_TODO_PENDING = 'REQUEST_UPDATE_TODO_PENDING';
export const REQUEST_UPDATE_TODO_SUCCESS = 'REQUEST_UPDATE_TODO_SUCCESS';
export const REQUEST_UPDATE_TODO_FAILED = 'REQUEST_UPDATE_TODO_FAILED';

export const REQUEST_DELETE_TODO_PENDING = 'REQUEST_DELETE_TODO_PENDING';
export const REQUEST_DELETE_TODO_SUCCESS = 'REQUEST_DELETE_TODO_SUCCESS';
export const REQUEST_DELETE_TODO_FAILED = 'REQUEST_DELETE_TODO_FAILED';

export const GET_TODOS = 'GET_TODOS';

export const ADD_TODO = 'ADD_TODO';

export const DELETE_TODO = 'DELETE_TODO';

export const UPDATE_TODO = 'UPDATE_TODO';
